name: master branch CI

on:
  push:
    branches: 
      - master
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: yarn install
    - run: yarn build
    - run: yarn test
    - name: Login to GitHub Package Repository
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login docker.pkg.github.com -u literallyanything -p ${GH_TOKEN}
    - name: Build Docker Image & Push 
      run: yarn docker-build-prod --repository=docker.pkg.github.com/magda-data/magda --version=${GITHUB_SHA}
